### ISSUE TITLE
reportFileAccessEvent 127: Cannot report file access event to SmartServer: /src/1

### ISSUE THREAD

**Issue by zhiqiangx** [Intel-bigdata/SSM#1074]
2017-09-12 13:46:07,078 ERROR org.apache.hadoop.hdfs.DFSClient.reportFileAccessEvent 127: Cannot report file access event to SmartServer: /src/1 , for: SSM services not ready...
	at org.smartdata.server.SmartRpcServer.checkIfActive(SmartRpcServer.java:139)
	at org.smartdata.server.SmartRpcServer.reportFileAccessEvent(SmartRpcServer.java:233)
	at org.smartdata.protocol.protobuffer.ServerProtocolsServerSideTranslator.reportFileAccessEvent(ServerProtocolsServerSideTranslator.java:324)
	at org.smartdata.protocol.ClientServerProto$protoService$2.callBlockingMethod(ClientServerProto.java:1189)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2045)
 , report mechanism will be disabled now in this instance.
2017-09-12 13:46:18,359 INFO org.smartdata.server.rest.RuleRestApi.stop 97: Stop rule6

**Comment by qiyuangong** [comment]
SSM server is not ready, or SSM server is not configured in `hdfs-site.xml`. More details can be found in [ssm-deployment-guide](https://github.com/Intel-bigdata/SSM/blob/trunk/docs/ssm-deployment-guide.md).

Issue closed.
