### ISSUE TITLE
Fix random failure of TestActionRestApi

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1107]
java.lang.AssertionError: 
Expected :1.0
Actual   :0.0
 <Click to see difference>

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:519)
	at org.junit.Assert.assertEquals(Assert.java:609)
	at org.smartdata.integration.TestActionRestApi.testAction(TestActionRestApi.java:134)
	at org.smartdata.integration.TestActionRestApi.testActionsInSequence(TestActionRestApi.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)

**Comment by littlezhou** [comment]
Done!
