### ISSUE TITLE
Failed to initialize database due to CREATE INDEX file_diff_idx ON file_diff (src)

### ISSUE THREAD

**Issue by PHILO-HE** [Intel-bigdata/SSM#1150]
2017-09-23 12:05:02,693 DEBUG org.smartdata.metastore.utils.MetaStoreUtils.initializeDataBase 298: CREATE INDEX file_diff_idx ON file_diff (src);
2017-09-23 12:05:02,715 ERROR org.smartdata.server.SmartServer.main 387: Failed to create SmartServer
org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 3072 bytes
	at org.smartdata.metastore.MetaStore.initializeDataBase(MetaStore.java:1158)
	at org.smartdata.metastore.MetaStore.formatDataBase(MetaStore.java:1166)
	at org.smartdata.metastore.utils.MetaStoreUtils.formatDatabase(MetaStoreUtils.java:325)
	at org.smartdata.server.SmartServer.processWith(SmartServer.java:145)
	at org.smartdata.server.SmartServer.launchWith(SmartServer.java:361)
	at org.smartdata.server.SmartServer.main(SmartServer.java:367)
	at org.smartdata.server.SmartDaemon.start(SmartDaemon.java:43)
	at org.smartdata.server.SmartDaemon.main(SmartDaemon.java:62)

**Comment by qiyuangong** [comment]
Change then length of file_diff.src.
```
src varchar(1000) NOT NULL
```

**Comment by PHILO-HE** [comment]
OK. Thanks!
