### ISSUE TITLE
Fix receate access count table issue

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1157]
2017-09-24 15:33:16,184 ERROR org.smartdata.metastore.dao.TableAddOpListener.run 60: Add AccessCount Table accessCount_1506238320000_1506238380000 error
org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE accessCount_1506238320000_1506238380000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'accessCount_1506238320000_1506238380000' already exists
	at org.smartdata.metastore.MetaStore.aggregateTables(MetaStore.java:1176)
	at org.smartdata.metastore.dao.AccessCountTableAggregator.aggregate(AccessCountTableAggregator.java:39)
	at org.smartdata.metastore.dao.TableAddOpListener$1.run(TableAddOpListener.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by littlezhou** [comment]
Done!
