### ISSUE TITLE
SSM service not ready

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#1177]
```
2017-09-28 10:50:06,528 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 7997 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,529 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8008 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,529 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8009 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,530 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8015 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,530 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8017 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,531 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8019 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,531 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8031 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,532 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8047 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,532 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8056 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,533 INFO org.smartdata.server.engine.cmdlet.CmdletDispatcher.dispatch 63: Dispatching cmdlet 8061 to executor service class org.smartdata.server.engine.cmdlet.LocalCmdletExecutorService
2017-09-28 10:50:06,535 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-09-28 10:50:06,535 WARN org.apache.hadoop.security.UserGroupInformation.doAs 1923: PriviledgedActionException as:root (auth:SIMPLE) cause:org.apache.hadoop.ipc.RetriableException: SSM services not ready...
2017-09-28 10:50:06,535 INFO org.apache.hadoop.ipc.Server.run 2237: IPC Server handler 36 on 7042, call org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer.reportFileAccessEvent from 192.168.50.2:56186 Call#15727 Retry#0
org.apache.hadoop.ipc.RetriableException: SSM services not ready...
        at org.smartdata.server.SmartRpcServer.checkIfActive(SmartRpcServer.java:139)
        at org.smartdata.server.SmartRpcServer.reportFileAccessEvent(SmartRpcServer.java:233)
        at org.smartdata.protocol.protobuffer.ServerProtocolsServerSideTranslator.reportFileAccessEvent(ServerProtocolsServerSideTranslator.java:324)
        at org.smartdata.protocol.ClientServerProto$protoService$2.callBlockingMethod(ClientServerProto.java:1189)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2212)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2210)
2017-09-28 10:50:06,535 ERROR org.apache.hadoop.hdfs.DFSClient.reportFileAccessEvent 127: Cannot report file access event to SmartServer: /src/36564a83-a350-4d42-92b6-506ce7104ecb , for: SSM services not ready...
        at org.smartdata.server.SmartRpcServer.checkIfActive(SmartRpcServer.java:139)
        at org.smartdata.server.SmartRpcServer.reportFileAccessEvent(SmartRpcServer.java:233)
        at org.smartdata.protocol.protobuffer.ServerProtocolsServerSideTranslator.reportFileAccessEvent(ServerProtocolsServerSideTranslator.java:324)
        at org.smartdata.protocol.ClientServerProto$protoService$2.callBlockingMethod(ClientServerProto.java:1189)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2212)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2210)
 , report mechanism will be disabled now in this instance.

```

**Comment by qiyuangong** [comment]
SSM is in safe model. 
Issue closed. Thanks @littlezhou
