### ISSUE TITLE
"Specified key was too long" when init DB using MySQL 5.6

### ISSUE THREAD

**Issue by timmyyao** [Intel-bigdata/SSM#1291]
MySQL version: mysql  Ver 14.14 Distrib 5.6.36, for Linux (x86_64) using  EditLine wrapper

2017-10-23 17:42:45,296 ERROR org.smartdata.server.SmartServer.main 380: Failed to create SmartServer
org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at org.smartdata.metastore.MetaStore.initializeDataBase(MetaStore.java:1261)
        at org.smartdata.metastore.MetaStore.formatDataBase(MetaStore.java:1269)
        at org.smartdata.metastore.utils.MetaStoreUtils.formatDatabase(MetaStoreUtils.java:329)
        at org.smartdata.server.SmartServer.processWith(SmartServer.java:143)
        at org.smartdata.server.SmartServer.launchWith(SmartServer.java:354)
        at org.smartdata.server.SmartServer.main(SmartServer.java:360)
        at org.smartdata.server.SmartDaemon.start(SmartDaemon.java:43)
        at org.smartdata.server.SmartDaemon.main(SmartDaemon.java:62)
Caused by: org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at org.smartdata.metastore.utils.MetaStoreUtils.initializeDataBase(MetaStoreUtils.java:306)
        at org.smartdata.metastore.MetaStore.initializeDataBase(MetaStore.java:1259)
        ... 7 more
Caused by: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at org.smartdata.metastore.utils.MetaStoreUtils.executeSql(MetaStoreUtils.java:316)
        at org.smartdata.metastore.utils.MetaStoreUtils.initializeDataBase(MetaStoreUtils.java:303)
        ... 8 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
        at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2489)
        at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
        at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
        at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
        at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
        at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:418)
        at org.smartdata.metastore.utils.MetaStoreUtils.executeSql(MetaStoreUtils.java:314)
        ... 9 more

**Comment by qiyuangong** [comment]
Already done. Issue closed.
