### ISSUE TITLE
NoClassDefFoundError when start ssm.

### ISSUE THREAD

**Issue by zhiqiangx** [Intel-bigdata/SSM#1310]
MultiException[java.lang.NoClassDefFoundError: javax/ws/rs/core/Link, java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy15, java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy15]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:842)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.apache.zeppelin.server.SmartZeppelinServer.start(SmartZeppelinServer.java:240)
	at org.smartdata.server.SmartServer.run(SmartServer.java:238)
	at org.smartdata.server.SmartServer.processWith(SmartServer.java:151)
	at org.smartdata.server.SmartServer.launchWith(SmartServer.java:354)
	at org.smartdata.server.SmartServer.main(SmartServer.java:360)
	at org.smartdata.server.SmartDaemon.start(SmartDaemon.java:43)
	at org.smartdata.server.SmartDaemon.main(SmartDaemon.java:62)

**Comment by huafengw** [comment]
Please try to revert this commit and try again : https://github.com/Intel-bigdata/SSM/commit/ae1ab795c19a25e5c6aad8c565e85a5eeba47e48
