### ISSUE TITLE
MetaStore and druid problem when fetching 40M files from namespace

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#1554]
```
2018-01-22 15:49:00,984 ERROR com.alibaba.druid.pool.DruidDataSource.removeAbandoned 2307: abandon connection, owner thread: pool-13-thread-1, connected at : 1516606955410, open stackTrace
        at java.lang.Thread.getStackTrace(Thread.java:1589)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1149)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:670)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1073)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1065)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:104)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:711)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:761)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)
        at org.smartdata.metastore.dao.FileInfoDao.getPathFids(FileInfoDao.java:91)
        at org.smartdata.metastore.MetaStore.getFileIDs(MetaStore.java:309)
        at org.smartdata.hdfs.metric.fetcher.CachedListFetcher$FetchTask.run(CachedListFetcher.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
ownerThread current state is RUNNABLE, current stackTrace
        at java.util.Arrays.copyOf(Arrays.java:2367)
        at java.lang.String.concat(String.java:1975)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:357)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:99)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:711)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:761)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)
        at org.smartdata.metastore.dao.FileInfoDao.getPathFids(FileInfoDao.java:91)
        at org.smartdata.metastore.MetaStore.getFileIDs(MetaStore.java:309)
        at org.smartdata.hdfs.metric.fetcher.CachedListFetcher$FetchTask.run(CachedListFetcher.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by qiyuangong** [comment]
```
org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [CREATE TABLE accessCount_1516794240000_1516794245000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)]; SQL state [HY000]; error code [3]; Error writing file './test/accessCount_1516794240000_1516794245000.frm' (Errcode: 28); nested exception is java.sql.SQLException: Error writing file './test/accessCount_1516794240000_1516794245000.frm' (Errcode: 28)
        at org.smartdata.metastore.MetaStore.execute(MetaStore.java:629)
        at org.smartdata.metastore.dao.AccessEventAggregator.createTable(AccessEventAggregator.java:79)
        at org.smartdata.metastore.dao.AccessEventAggregator.addAccessEvents(AccessEventAggregator.java:64)
        at org.smartdata.metastore.dao.AccessCountTableManager.onAccessEventsArrived(AccessCountTableManager.java:115)
        at org.smartdata.server.engine.data.AccessEventFetcher$FetchTask.run(AccessEventFetcher.java:100)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by qiyuangong** [comment]
```
java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeInfoWithStorage[192.168.50.51:50010,DS-34f6d0b0-7bab-43b9-aeae-94ed2e526277,DISK]], original=[DatanodeInfoWithStorage[192.168.50.51:50010,DS-34f6d0b0-7bab-43b9-aeae-94ed2e526277,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-failure.policy' in its configuration.
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.findNewDatanode(DFSOutputStream.java:925)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:988)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1156)

```

**Comment by littlezhou** [comment]
Can not reproduce
