### ISSUE TITLE
Sync error after triggering the rule

### ISSUE THREAD

**Issue by PHILO-HE** [Intel-bigdata/SSM#1594]
2018-02-08 16:21:04,894 ERROR org.smartdata.hdfs.scheduler.CopyScheduler.run 646: CopyScheduler Run Error
org.smartdata.metastore.MetaStoreException: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 3
	at org.smartdata.metastore.MetaStore.getFile(MetaStore.java:280)
	at org.smartdata.hdfs.scheduler.CopyScheduler.directSync(CopyScheduler.java:381)
	at org.smartdata.hdfs.scheduler.CopyScheduler.batchDirectSync(CopyScheduler.java:283)
	at org.smartdata.hdfs.scheduler.CopyScheduler.access$700(CopyScheduler.java:57)
	at org.smartdata.hdfs.scheduler.CopyScheduler$ScheduleTask.run(CopyScheduler.java:642)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 3
	at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:74)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:795)
	at org.smartdata.metastore.dao.FileInfoDao.getByPath(FileInfoDao.java:79)
	at org.smartdata.metastore.MetaStore.getFile(MetaStore.java:276)
	... 11 more

**Comment by qiyuangong** [comment]
Caused by dirty metastore records. Fixed after removing all these records. Thanks to @PHILO-HE .
Issue closed
