### ISSUE TITLE
NoSuchMethodError occurs for copy2s3 action

### ISSUE THREAD

**Issue by PHILO-HE** [Intel-bigdata/SSM#1596]
For hadoop 2.7.3, the following error is reported. If laws-java-sdk-core-1.10.6.jar and aws-java-sdk-s3-1.10.6.jar are removed in ${SMART_HOME}/lib, this action can be executed successfully.

Action starts at Fri Feb 09 11:21:11 CST 2018 : Read /ssm/data1
Copy from /ssm/data1 to s3a://xxxctest/data1-copy
java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManagerConfiguration.setMultipartUploadThreshold(I)V
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:285)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.smartdata.hdfs.CompatibilityHelper27.getS3outputStream(CompatibilityHelper27.java:166)
	at org.smartdata.hdfs.action.Copy2S3Action.copySingleFile(Copy2S3Action.java:130)
	at org.smartdata.hdfs.action.Copy2S3Action.execute(Copy2S3Action.java:99)
	at org.smartdata.action.SmartAction.run(SmartAction.java:124)
	at org.smartdata.server.engine.cmdlet.Cmdlet.runAllActions(Cmdlet.java:94)
	at org.smartdata.server.engine.cmdlet.Cmdlet.run(Cmdlet.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by qiyuangong** [comment]
Thank you @PHILO-HE .
I have added this issue and solution to `s3-support.md`.

**Comment by qiyuangong** [comment]
Issue closed.
