### ISSUE TITLE
Fix NPE in batch cmdlet sync

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1628]
org.smartdata.metastore.MetaStoreException: java.lang.NullPointerException
	at org.smartdata.metastore.MetaStore.insertActions(MetaStore.java:1043)
	at org.smartdata.server.engine.CmdletManager.batchSyncCmdAction(CmdletManager.java:380)
	at org.smartdata.server.engine.CmdletManager.access$100(CmdletManager.java:80)
	at org.smartdata.server.engine.CmdletManager$ScheduleTask.run(CmdletManager.java:1055)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.smartdata.metastore.dao.ActionDao$1.setValues(ActionDao.java:252)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:950)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
	at org.smartdata.metastore.dao.ActionDao.replace(ActionDao.java:248)
	at org.smartdata.metastore.MetaStore.insertActions(MetaStore.java:1041)
	... 10 more
2018-03-09 10:18:18,536 ERROR akka.actor.OneForOneStrategy.apply$mcV$sp 66: 
java.lang.NullPointerException
	at org.smartdata.server.engine.CmdletManager.inferCmdletStatus(CmdletManager.java:975)
	at org.smartdata.server.engine.CmdletManager.onStatusReport(CmdletManager.java:908)
	at org.smartdata.server.engine.CmdletManager.updateStatus(CmdletManager.java:891)
	at org.smartdata.server.engine.cmdlet.agent.AgentMaster$MasterActor.handleAgentMessage(AgentMaster.java:256)
	at org.smartdata.server.engine.cmdlet.agent.AgentMaster$MasterActor.onReceive(AgentMaster.java:231)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by PHILO-HE** [comment]
Will fix this issue in PR #1607.

**Comment by PHILO-HE** [comment]
Also fix by PR #1648
