### ISSUE TITLE
SSM Compression on Terasort 1TB (2*500GB) Error message

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#2051]
Current code base passed 1TB Terasort and SparkTerasort on 3GB (391MB *8) on Hadoop 2.7. But failed on 1TB (500*2) on Hadoop 3.2.

Error logs on Hadoop 3.2:
```
2019-02-24 11:04:22,042 ERROR terasort.TeraSort: Direct buffer memory
Got an exception while reading splits java.io.IOException: Filesystem closed
        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:472)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:743)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:827)
        at org.apache.hadoop.hdfs.SmartCompressionInputStream.rawReadInt(SmartCompressionInputStream.java:142)
        at org.apache.hadoop.hdfs.SmartCompressionInputStream.getCompressedData(SmartCompressionInputStream.java:121)
        at org.apache.hadoop.hdfs.SmartCompressionInputStream.seek(SmartCompressionInputStream.java:182)
        at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:65)
        at org.apache.hadoop.examples.terasort.TeraInputFormat$TeraRecordReader.initialize(TeraInputFormat.java:231)
        at org.apache.hadoop.examples.terasort.TeraInputFormat$1.run(TeraInputFormat.java:153)

Got an exception while reading splits java.io.IOException: Filesystem closed
        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:472)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:743)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:827)
        at org.apache.hadoop.hdfs.SmartCompressionInputStream.rawReadInt(SmartCompressionInputStream.java:142)
        at org.apache.hadoop.hdfs.SmartCompressionInputStream.getCompressedData(SmartCompressionInputStream.java:121)
        at org.apache.hadoop.hdfs.SmartCompressionInputStream.seek(SmartCompressionInputStream.java:182)
        at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:65)
        at org.apache.hadoop.examples.terasort.TeraInputFormat$TeraRecordReader.initialize(TeraInputFormat.java:231)
        at org.apache.hadoop.examples.terasort.TeraInputFormat$1.run(TeraInputFormat.java:153)

```

**Comment by qiyuangong** [comment]
Updates:
Errors in namenode
```
2019-02-25 14:54:55,175 INFO org.apache.hadoop.ipc.Server: IPC Server handler 19 on 9000, call Call#1 Retry#0 org.apache.hadoop.hdfs.protocol.ClientProtocol.getXAttrs from 10.1.2.205:44010
java.io.IOException: At least one of the attributes provided was not found.
        at org.apache.hadoop.hdfs.server.namenode.FSDirXAttrOp.getXAttrs(FSDirXAttrOp.java:114)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getXAttrs(FSNamesystem.java:7713)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getXAttrs(NameNodeRpcServer.java:2181)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getXAttrs(ClientNamenodeProtocolServerSideTranslatorPB.java:1627)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1687)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
2019-02-25 14:54:56,965 INFO org.apache.hadoop.ipc.Server: IPC Server handler 85 on 9000, call Call#1 Retry#0 org.apache.hadoop.hdfs.protocol.ClientProtocol.getXAttrs from 10.1.2.205:44012

```
