### ISSUE TITLE
TestMoverPool failed

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#254]
```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 64.674 sec <<< FAILURE!
testStopAndRestartMovers(org.smartdata.server.actions.mover.TestMoverPool)  Time elapsed: 2.774 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.smartdata.server.actions.mover.TestMoverPool.testStopAndRestartMovers(TestMoverPool.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by timmyyao** [comment]
I removed a method in MoverPool as it can not perform the expected function in the latest version.
