### ISSUE TITLE
Fix SmartServer test failures

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#436]

**Comment by qiyuangong** [comment]
**Current failures**
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.869 sec <<< FAILURE! - in org.smartdata.server.TestSmartServerCli
testConfNameNodeRPCAddr(org.smartdata.server.TestSmartServerCli)  Time elapsed: 4.869 sec  <<< FAILURE!
java.lang.AssertionError: Should not work without specifying dfs.smart.namenode.rpcserver
	at org.junit.Assert.fail(Assert.java:88)
	at org.smartdata.server.TestSmartServerCli.testConfNameNodeRPCAddr(TestSmartServerCli.java:56)
```

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.805 sec <<< FAILURE! - in org.smartdata.server.TestSmartServerReConfig
setUp(org.smartdata.server.TestSmartServerReConfig)  Time elapsed: 7.805 sec  <<< FAILURE!
java.lang.AssertionError: Should fail without specifying Namanode
	at org.junit.Assert.fail(Assert.java:88)
	at org.smartdata.server.TestSmartServerReConfig.setUp(TestSmartServerReConfig.java:81)
```

**Current errors:**
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.317 sec <<< FAILURE! - in org.smartdata.server.TestSmartAdmin
test(org.smartdata.server.TestSmartAdmin)  Time elapsed: 6.317 sec  <<< ERROR!
java.net.BindException: Problem binding to [0.0.0.0:7042] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.hadoop.ipc.Server.bind(Server.java:408)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:574)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:2215)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:951)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:534)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:509)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:796)
	at org.smartdata.server.SmartRpcServer.<init>(SmartRpcServer.java:82)
	at org.smartdata.server.SmartServer.initWith(SmartServer.java:75)
	at org.smartdata.server.SmartServer.processWith(SmartServer.java:117)
	at org.smartdata.server.SmartServer.launchWith(SmartServer.java:314)
	at org.smartdata.server.SmartServer.launchWith(SmartServer.java:302)
	at org.smartdata.server.TestSmartAdmin.test(TestSmartAdmin.java:72)
```

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.156 sec <<< FAILURE! - in org.smartdata.server.TestSmartServerLogin
loginSmartServerUsingKeytab(org.smartdata.server.TestSmartServerLogin)  Time elapsed: 6.155 sec  <<< ERROR!
java.net.BindException: Problem binding to [0.0.0.0:7042] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.hadoop.ipc.Server.bind(Server.java:408)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:574)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:2215)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:951)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:534)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:509)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:796)
	at org.smartdata.server.SmartRpcServer.<init>(SmartRpcServer.java:82)
	at org.smartdata.server.SmartServer.initWith(SmartServer.java:75)
	at org.smartdata.server.SmartServer.processWith(SmartServer.java:117)
	at org.smartdata.server.SmartServer.launchWith(SmartServer.java:314)
	at org.smartdata.server.SmartServer.launchWith(SmartServer.java:302)
	at org.smartdata.server.TestSmartServerLogin.loginSmartServerUsingKeytab(TestSmartServerLogin.java:86)

```
