### ISSUE TITLE
Get action from DB error

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#552]
2017-07-04 09:23:55,298 ERROR engine.CmdletManager (CmdletManager.java:getNextCmdletToRun(231)) - Get Actions from DB with IDs [3] error!
java.io.IOException: org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select * from actions WHERE aid IN (?)]; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.smartdata.server.engine.CmdletManager.getNextCmdletToRun(CmdletManager.java:232)
	at org.smartdata.server.engine.CmdletManager$ScheduleTask.run(CmdletManager.java:521)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select * from actions WHERE aid IN (?)]; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.smartdata.metastore.MetaStore.getActionsTableItem(MetaStore.java:655)
	at org.smartdata.server.engine.CmdletManager.getNextCmdletToRun(CmdletManager.java:221)
	... 8 more
Caused by: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select * from actions WHERE aid IN (?)]; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:711)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:761)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)
	at org.smartdata.metastore.dao.ActionDao.getByIds(ActionDao.java:65)
	at org.smartdata.metastore.MetaStore.getActionsTableItem(MetaStore.java:653)
	... 9 more
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:822)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2714)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:145)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 15 more

**Comment by littlezhou** [comment]
Fixed!
