### ISSUE TITLE
accessCount aggregate sql error

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#559]
```
[ERROR] [07/04/2017 12:51:14.107] [RuleExecutor] Rule 1 exception
org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DROP TABLE IF EXISTS 'VIR_ACC_CNT_TAB_1_accessCount_60000';]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''VIR_ACC_CNT_TAB_1_accessCount_60000'' at line 1
	at org.smartdata.metastore.MetaStore.execute(MetaStore.java:479)
	at org.smartdata.server.engine.rule.RuleExecutor.executeFileRuleQuery(RuleExecutor.java:116)
	at org.smartdata.server.engine.rule.RuleExecutor.run(RuleExecutor.java:265)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DROP TABLE IF EXISTS 'VIR_ACC_CNT_TAB_1_accessCount_60000';]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''VIR_ACC_CNT_TAB_1_accessCount_60000'' at line 1
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:443)
	at org.smartdata.metastore.dao.ManagementDao.execute(ManagementDao.java:25)
	at org.smartdata.metastore.MetaStore.execute(MetaStore.java:477)
	... 9 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''VIR_ACC_CNT_TAB_1_accessCount_60000'' at line 1
	at sun.reflect.GeneratedConstructorAccessor39.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2489)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:418)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:435)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
	... 12 more
```

**Comment by huafengw** [comment]
```
[ERROR] [07/04/2017 13:41:57.818] [RuleExecutor] Rule 1 exception
org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE VIR_ACC_CNT_TAB_1_accessCount_60000 AS SELECT * FROM (SELECT fid, SUM(count) AS count FROM (
SELECT fid, count FROM accessCount_1499146880000_1499146885000
UNION ALL
SELECT fid, count FROM accessCount_1499146885000_1499146890000
UNION ALL
SELECT fid, count FROM accessCount_1499146890000_1499146895000
UNION ALL
SELECT fid, count FROM accessCount_1499146895000_1499146900000
UNION ALL
SELECT fid, count FROM accessCount_1499146900000_1499146905000
UNION ALL
SELECT fid, count FROM accessCount_1499146905000_1499146910000
UNION ALL
SELECT fid, count FROM accessCount_1499146910000_1499146915000
) GROUP BY fid );]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Every derived table must have its own alias
	at org.smartdata.metastore.MetaStore.execute(MetaStore.java:479)
	at org.smartdata.server.engine.rule.RuleExecutor.executeFileRuleQuery(RuleExecutor.java:116)
	at org.smartdata.server.engine.rule.RuleExecutor.run(RuleExecutor.java:265)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by qiyuangong** [comment]
In mysql, every query should be given a alias, [MySQL UNION - Every derived table must have its own alias] (https://stackoverflow.com/questions/25340979/mysql-union-every-derived-table-must-have-its-own-alias).

**Comment by qiyuangong** [comment]
Correct sql in mysql.
```sql
CREATE TABLE test AS SELECT * FROM
	(SELECT  fid, SUM(count) AS count FROM
    (SELECT fid, count FROM blank_access_count_info UNION ALL SELECT fid, count FROM blank_access_count_info) AS tmp
    GROUP BY fid) as t;
```
