### ISSUE TITLE
archive failed

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#582]
```
2017-07-05 14:23:48,935 ERROR rule.RuleExecutor (RuleExecutor.java:executeFileRuleQuery(121)) - Rule 2 exception
org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT path FROM files WHERE ((((SELECT policy_name FROM storage_policy WHERE sid = files.sid) <> 'COLD') AND ((path LIKE '/testArchive/%') AND ((strftime('%s','now') * 1000 - modification_time) > 600000))));]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION test.strftime does not exist
	at org.smartdata.metastore.MetaStore.executeFilesPathQuery(MetaStore.java:502)
	at org.smartdata.server.engine.rule.RuleExecutor.executeFileRuleQuery(RuleExecutor.java:115)
	at org.smartdata.server.engine.rule.RuleExecutor.run(RuleExecutor.java:269)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT path FROM files WHERE ((((SELECT policy_name FROM storage_policy WHERE sid = files.sid) <> 'COLD') AND ((path LIKE '/testArchive/%') AND ((strftime('%s','now') * 1000 - modification_time) > 600000))));]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION test.strftime does not exist
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474)
	at org.smartdata.metastore.dao.MetaStoreHelper.getFilesPath(MetaStoreHelper.java:42)
	at org.smartdata.metastore.MetaStore.executeFilesPathQuery(MetaStore.java:500)
	... 9 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION test.strftime does not exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2363)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeQuery(StatementProxyImpl.java:211)
	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:140)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:458)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
	... 12 more
```

**Comment by qiyuangong** [comment]
Thanks @huafengw .
This issue happened on mysql because `strftime` in not supported by mysql. I am trying to fix it right now.

**Comment by littlezhou** [comment]
Done!
