### ISSUE TITLE
SQLException on ActionDao and CmdletDao

### ISSUE THREAD

**Issue by manuzhang** [Intel-bigdata/SSM#601]
* ActionDao
```
[ERROR] [07/06/2017 03:21:42.932] [DruidPooledPreparedStatement] getFetchDirection error
java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:69)
	at org.sqlite.jdbc3.JDBC3ResultSet.getFetchDirection(JDBC3ResultSet.java:116)
	at org.sqlite.jdbc3.JDBC3Statement.getFetchDirection(JDBC3Statement.java:324)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:2537)
	at com.alibaba.druid.filter.FilterAdapter.statement_getFetchDirection(FilterAdapter.java:2514)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:2535)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getFetchDirection(StatementProxyImpl.java:283)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:98)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:355)
	at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1521)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:627)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:794)
	at org.smartdata.metastore.dao.ActionDao.getById(ActionDao.java:56)
	at org.smartdata.metastore.MetaStore.getActionById(MetaStore.java:679)
	at org.smartdata.server.engine.CmdletManager.getActionInfo(CmdletManager.java:354)
```

* CmdletDao 

```
[ERROR] [07/06/2017 03:21:34.994] [DruidPooledPreparedStatement] getFetchDirection error
java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:69)
	at org.sqlite.jdbc3.JDBC3ResultSet.getFetchDirection(JDBC3ResultSet.java:116)
	at org.sqlite.jdbc3.JDBC3Statement.getFetchDirection(JDBC3Statement.java:324)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:2537)
	at com.alibaba.druid.filter.FilterAdapter.statement_getFetchDirection(FilterAdapter.java:2514)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:2535)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getFetchDirection(StatementProxyImpl.java:283)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:98)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:355)
	at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1521)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:627)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:941)
	at org.smartdata.metastore.dao.CmdletDao.update(CmdletDao.java:118)
```

**Comment by manuzhang** [comment]
Verified this happens with sqlite but is find with mysql

**Comment by qiyuangong** [comment]
Thanks @manuzhang .
Sqlite is not well designed for multiple connections and concurrency. It will lock the database file during write operations. However, SSM will have multiple threads with multiple connections trying to write to Database. So, it may occur `SQLite_Busy` or `database file locked` on sqlite.

**Comment by littlezhou** [comment]
will not fix for now
