### ISSUE TITLE
AccessCountTable Error "table already exists"

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#628]
```
org.smartdata.metastore.MetaStoreException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE accessCount_1499652180000_1499652240000 as SELECT fid, SUM(count) as count FROM (SELECT * FROM accessCount_1499652195000_1499652200000 UNION ALL SELECT * FROM accessCount_1499652200000_1499652205000 UNION ALL SELECT * FROM accessCount_1499652205000_1499652210000 UNION ALL SELECT * FROM accessCount_1499652210000_1499652215000 UNION ALL SELECT * FROM accessCount_1499652225000_1499652230000 UNION ALL SELECT * FROM accessCount_1499652230000_1499652235000) tmp GROUP BY fid]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'accessCount_1499652180000_1499652240000' already exists
	at org.smartdata.metastore.MetaStore.execute(MetaStore.java:483)
	at org.smartdata.metastore.dao.AccessCountTableAggregator.aggregate(AccessCountTableAggregator.java:40)
	at org.smartdata.metastore.dao.TableAddOpListener$1.run(TableAddOpListener.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE accessCount_1499652180000_1499652240000 as SELECT fid, SUM(count) as count FROM (SELECT * FROM accessCount_1499652195000_1499652200000 UNION ALL SELECT * FROM accessCount_1499652200000_1499652205000 UNION ALL SELECT * FROM accessCount_1499652205000_1499652210000 UNION ALL SELECT * FROM accessCount_1499652210000_1499652215000 UNION ALL SELECT * FROM accessCount_1499652225000_1499652230000 UNION ALL SELECT * FROM accessCount_1499652230000_1499652235000) tmp GROUP BY fid]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'accessCount_1499652180000_1499652240000' already exists
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:443)
	at org.smartdata.metastore.dao.MetaStoreHelper.execute(MetaStoreHelper.java:25)
	at org.smartdata.metastore.MetaStore.execute(MetaStore.java:481)
	... 9 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'accessCount_1499652180000_1499652240000' already exists
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2489)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:418)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:435)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
	... 12 more
```

**Comment by huafengw** [comment]
Hopefully is fixed in #655
