### ISSUE TITLE
Build failed in test cases  

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#647]
Use command "mvn package -Pdist" to build trunk, see the following errors constantly,

[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ smart-server ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.smartdata.server.engine.cmdlet.TestCmdlet
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.405 s <<< FAILURE! - in org.smartdata.server.engine.cmdlet.TestCmdlet
[ERROR] testRunCmdlet(org.smartdata.server.engine.cmdlet.TestCmdlet)  Time elapsed: 1.289 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found
	at org.smartdata.server.engine.cmdlet.TestCmdlet.createCluster(TestCmdlet.java:57)

[INFO] Running org.smartdata.server.engine.rule.TestGetRuleInfo
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.127 s <<< FAILURE! - in org.smartdata.server.engine.rule.TestGetRuleInfo
[ERROR] testGetSingleRuleInfo(org.smartdata.server.engine.rule.TestGetRuleInfo)  Time elapsed: 0.058 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[ERROR] testMultiRules(org.smartdata.server.engine.rule.TestGetRuleInfo)  Time elapsed: 0.058 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[INFO] Running org.smartdata.server.engine.rule.TestRuleManager
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.565 s - in org.smartdata.server.engine.rule.TestRuleManager
[INFO] Running org.smartdata.server.engine.rule.TestSubmitRule
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.036 s <<< FAILURE! - in org.smartdata.server.engine.rule.TestSubmitRule
[ERROR] testSubmitRule(org.smartdata.server.engine.rule.TestSubmitRule)  Time elapsed: 0.036 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[INFO] Running org.smartdata.server.engine.TestCmdletManager
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.219 s <<< FAILURE! - in org.smartdata.server.engine.TestCmdletManager
[ERROR] testGetListDeleteCmdlet(org.smartdata.server.engine.TestCmdletManager)  Time elapsed: 0.035 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[ERROR] testCreateFromDescriptor(org.smartdata.server.engine.TestCmdletManager)  Time elapsed: 0.055 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[ERROR] testAPI(org.smartdata.server.engine.TestCmdletManager)  Time elapsed: 0.033 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[ERROR] wrongCmdlet(org.smartdata.server.engine.TestCmdletManager)  Time elapsed: 0.033 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[ERROR] testWithoutCluster(org.smartdata.server.engine.TestCmdletManager)  Time elapsed: 0.03 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[ERROR] testFileLock(org.smartdata.server.engine.TestCmdletManager)  Time elapsed: 0.029 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[INFO] Running org.smartdata.server.TestSmartAdmin
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.028 s <<< FAILURE! - in org.smartdata.server.TestSmartAdmin
[ERROR] test(org.smartdata.server.TestSmartAdmin)  Time elapsed: 0.028 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[INFO] Running org.smartdata.server.TestSmartServer
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.079 s <<< FAILURE! - in org.smartdata.server.TestSmartServer
[ERROR] test(org.smartdata.server.TestSmartServer)  Time elapsed: 1.079 s  <<< ERROR!
java.net.BindException: Problem binding to [0.0.0.0:7042] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
	at org.smartdata.server.TestSmartServer.setUp(TestSmartServer.java:53)
Caused by: java.net.BindException: Address already in use
	at org.smartdata.server.TestSmartServer.setUp(TestSmartServer.java:53)

[INFO] Running org.smartdata.server.TestSmartServerCli
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.028 s <<< FAILURE! - in org.smartdata.server.TestSmartServerCli
[ERROR] testConfNameNodeRPCAddr(org.smartdata.server.TestSmartServerCli)  Time elapsed: 0.028 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found
	at org.smartdata.server.TestSmartServerCli.testConfNameNodeRPCAddr(TestSmartServerCli.java:40)

[INFO] Running org.smartdata.server.TestSmartServerLogin
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.213 s <<< FAILURE! - in org.smartdata.server.TestSmartServerLogin
[ERROR] loginSmartServerUsingKeytab(org.smartdata.server.TestSmartServerLogin)  Time elapsed: 0.211 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found
	at org.smartdata.server.TestSmartServerLogin.initConf(TestSmartServerLogin.java:54)
	at org.smartdata.server.TestSmartServerLogin.loginSmartServerUsingKeytab(TestSmartServerLogin.java:84)

[INFO] Running org.smartdata.server.TestSmartServerReConfig
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.051 s <<< FAILURE! - in org.smartdata.server.TestSmartServerReConfig
[ERROR] setUp(org.smartdata.server.TestSmartServerReConfig)  Time elapsed: 0.051 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found
	at org.smartdata.server.TestSmartServerReConfig.setUp(TestSmartServerReConfig.java:54)

[INFO] Running org.smartdata.server.tools.TestSmartShell
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 s - in org.smartdata.server.tools.TestSmartShell
[INFO] Running org.smartdata.server.tools.TestSubmitRuleThroughCli
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in org.smartdata.server.tools.TestSubmitRuleThroughCli
[ERROR] test(org.smartdata.server.tools.TestSubmitRuleThroughCli)  Time elapsed: 0.042 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.util.JvmPauseMonitor: method <init>()V not found

[INFO] Running org.smartdata.server.util.TestJsonUtil
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.075 s - in org.smartdata.server.util.TestJsonUtil
[INFO] 
[INFO] Results:
[INFO]

**Comment by ChenSammi** [comment]
Can someone look into this issue?  The unit test fails every time. If we cannot fix it because of some reason, please comments them out, so the remaining unit test can got the change to run.

**Comment by huafengw** [comment]
Can you try `mvn install package -Pdist`?

**Comment by ChenSammi** [comment]
With latest source code, the unit test failed at Zeppelin server module which has no problem previously on Mac.

 Zeppelin: Server ................................... FAILURE [01:00 min]


org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"53.0","maxVersion":"53.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":null}
1499926153976	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1499926153977	DeferredSave.extensions.json	DEBUG	Save changes
1499926153977	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1499926153977	addons.xpi-utils	DEBUG	Updating add-on states
1499926153978	addons.xpi-utils	DEBUG	Writing add-ons list
1499926153979	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1499926153979	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1499926153980	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1499926153980	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.14
1499926153981	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1499926153981	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1499926153982	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1499926153982	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1499926153984	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1499926153984	addons.manager	DEBUG	Provider finished startup: XPIProvider
1499926153985	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1499926153985	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1499926153985	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1499926153986	addons.manager	DEBUG	Starting provider: GMPProvider
1499926153989	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1499926153989	addons.manager	DEBUG	Provider finished startup: GMPProvider
1499926153989	addons.manager	DEBUG	Starting provider: PluginProvider
1499926153989	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1499926153990	addons.manager	DEBUG	Provider finished startup: PluginProvider
1499926153990	addons.manager	DEBUG	Completed startup sequence
1499926154280	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1499926154280	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1499926154281	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1499926154285	DeferredSave.extensions.json	DEBUG	Starting write
1499926154374	addons.repository	DEBUG	No addons.json found.
1499926154375	DeferredSave.addons.json	DEBUG	Save changes
1499926154379	DeferredSave.addons.json	DEBUG	Starting timer
1499926154400	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1499926154400	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1499926154401	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1499926154423	DeferredSave.extensions.json	DEBUG	Write succeeded
1499926154424	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1499926154434	DeferredSave.addons.json	DEBUG	Starting write
1499926154452	DeferredSave.addons.json	DEBUG	Write succeeded
2017-07-12 23:09:15.603 plugin-container[30915:830247] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x983b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-07-12 23:09:15.605 plugin-container[30915:830247] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9b03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:123)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.apache.zeppelin.AbstractFunctionalSuite.firefox(AbstractFunctionalSuite.scala:82)
	at org.apache.zeppelin.AbstractFunctionalSuite$$anonfun$3.apply(AbstractFunctionalSuite.scala:60)
	at org.apache.zeppelin.AbstractFunctionalSuite$$anonfun$3.apply(AbstractFunctionalSuite.scala:60)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.zeppelin.AbstractFunctionalSuite$$anonfun$4.apply(AbstractFunctionalSuite.scala:61)
	at org.apache.zeppelin.AbstractFunctionalSuite$$anonfun$4.apply(AbstractFunctionalSuite.scala:61)
	at scala.collection.immutable.List.map(List.scala:277)
	at org.apache.zeppelin.AbstractFunctionalSuite.getDriver(AbstractFunctionalSuite.scala:61)
	at org.apache.zeppelin.AbstractFunctionalSuite.<init>(AbstractFunctionalSuite.scala:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:69)
	at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
	at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
	at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:2390)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2475)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.main(Runner.scala:860)
	at org.scalatest.tools.Runner.main(Runner.scala)
*** RUN ABORTED ***
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.zeppelin.AbstractFunctionalSuite
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:84)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  ...
  Cause: java.lang.RuntimeException: Could not initialize any driver
  at org.apache.zeppelin.AbstractFunctionalSuite.getDriver(AbstractFunctionalSuite.scala:64)
  at org.apache.zeppelin.AbstractFunctionalSuite.<init>(AbstractFunctionalSuite.scala:39)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at java.lang.Class.newInstance(Class.java:383)
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:69)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  ...

**Comment by huafengw** [comment]
I also met with this problem. Currently all the tests passed on travis. So if you want to verify your code change, you can submit a pull request to see whether all the tests passed.
