### ISSUE TITLE
smart server crashed when try to perform "read" action with invalid argument

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#652]
For "read" action, I tried to put the "/benchmarks/TestDFSIO/io_control/in_file_test_io_2" as the action argument, smart server crashed after a while because of out of memory. 

Here is the log,
```
017-07-10 19:11:08,002 INFO org.smartdata.metastore.MetaStore.execute 480: Execute sql = CREATE TABLE accessCount_1499739060000_1499739065000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)
2017-07-10 19:11:08,015 INFO org.smartdata.metastore.MetaStore.dropTable 462: Drop table = accessCount_1499738910000_1499738915000
2017-07-10 19:11:13,006 INFO org.smartdata.metastore.MetaStore.execute 480: Execute sql = CREATE TABLE accessCount_1499739065000_1499739070000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)
2017-07-10 19:11:13,018 INFO org.smartdata.metastore.MetaStore.dropTable 462: Drop table = accessCount_1499738915000_1499738920000
2017-07-10 19:11:18,002 INFO org.smartdata.metastore.MetaStore.execute 480: Execute sql = CREATE TABLE accessCount_1499739070000_1499739075000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)
2017-07-10 19:11:18,014 INFO org.smartdata.metastore.MetaStore.dropTable 462: Drop table = accessCount_1499738920000_1499738925000
2017-07-10 19:11:23,001 INFO org.smartdata.metastore.MetaStore.execute 480: Execute sql = CREATE TABLE accessCount_1499739075000_1499739080000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)
2017-07-10 19:11:23,010 INFO org.smartdata.metastore.MetaStore.dropTable 462: Drop table = accessCount_1499738925000_1499738930000
2017-07-10 19:11:28,572 INFO com.hazelcast.instance.Node.log 64: [localhost]:5701 [dev] [3.7.8] Running shutdown hook... Current state: ACTIVE
2017-07-10 19:11:28,573 INFO org.smartdata.server.engine.cmdlet.agent.AgentMaster.shutdown 100: Shutting down master akka.tcp://AgentMaster@127.0.0.1:7051/user/master...
2017-07-10 19:11:28,572 INFO org.smartdata.server.SmartServer.run 332: Shutting down SmartServer ... 
2017-07-10 19:11:28,572 INFO org.apache.zeppelin.server.SmartZeppelinServer.run 242: Shutting down Zeppelin Server ... 
2017-07-10 19:11:28,572 INFO com.hazelcast.core.LifecycleService.log 64: [localhost]:5701 [dev] [3.7.8] [localhost]:5701 is SHUTTING_DOWN
2017-07-10 19:11:28,674 INFO org.smartdata.server.engine.cmdlet.agent.AgentMaster.shutdown 104: Shutting down system akka.tcp://AgentMaster@127.0.0.1:7051...
2017-07-10 19:11:28,573 INFO org.smartdata.server.engine.RuleManager.stop 275: Stopping ...
2017-07-10 19:11:28,674 INFO org.smartdata.server.engine.RuleManager.stop 280: Stopped.
2017-07-10 19:11:28,674 INFO com.hazelcast.instance.Node.log 64: [localhost]:5701 [dev] [3.7.8] Shutting down connection manager...
2017-07-10 19:11:28,941 INFO org.smartdata.server.engine.cmdlet.agent.AgentMaster.shutdown 100: Shutting down master akka.tcp://AgentMaster@127.0.0.1:7051/user/master...
2017-07-10 19:11:29,165 INFO org.smartdata.metastore.MetaStore.execute 480: Execute sql = CREATE TABLE accessCount_1499739080000_1499739085000 (fid INTEGER NOT NULL, count INTEGER NOT NULL)
2017-07-10 19:11:29,396 WARN org.eclipse.jetty.util.component.AbstractLifeCycle.setFailed 212: FAILED org.eclipse.jetty.server.Server@c06d2b7: java.lang.OutOfMemoryError: PermGen space
java.lang.OutOfMemoryError: PermGen space
2017-07-10 19:11:29,396 INFO com.hazelcast.instance.Node.log 64: [localhost]:5701 [dev] [3.7.8] Shutting down node engine...
2017-07-10 19:11:29,395 INFO org.smartdata.server.engine.cmdlet.agent.AgentMaster.shutdown 104: Shutting down system akka.tcp://AgentMaster@127.0.0.1:7051...
2017-07-10 19:11:29,739 INFO org.smartdata.server.engine.StatesManager.stop 105: Stopping ...
2017-07-10 19:11:29,739 INFO org.smartdata.hdfs.HdfsStatesUpdateService.stop 86: Stopping ...
2017-07-10 19:11:29,981 INFO org.smartdata.hdfs.HdfsStatesUpdateService.stop 94: Stopped.
2017-07-10 19:11:29,982 INFO org.smartdata.server.engine.StatesManager.stop 116: Stopped.
2017-07-10 19:11:29,982 INFO org.apache.zeppelin.server.SmartZeppelinServer.stop 261: Shutting down Zeppelin Server ... 
2017-07-10 19:11:30,303 INFO org.smartdata.metastore.MetaStore.dropTable 462: Drop table = accessCount_1499738930000_1499738935000
2017-07-10 19:11:30,490 WARN org.eclipse.jetty.util.component.AbstractLifeCycle.setFailed 212: FAILED org.eclipse.jetty.server.Server@c06d2b7: java.lang.OutOfMemoryError: PermGen space
java.lang.OutOfMemoryError: PermGen space
2017-07-10 19:11:32,043 INFO com.hazelcast.instance.NodeExtension.log 64: [localhost]:5701 [dev] [3.7.8] Destroying node NodeExtension.
2017-07-10 19:11:32,043 INFO com.hazelcast.instance.Node.log 64: [localhost]:5701 [dev] [3.7.8] Hazelcast Shutdown is completed in 3369 ms.
2017-07-10 19:11:32,305 INFO com.hazelcast.core.LifecycleService.log 64: [localhost]:5701 [dev] [3.7.8] [localhost]:5701 is SHUTTING_DOWN
2017-07-10 19:11:32,305 INFO com.hazelcast.instance.Node.log 64: [localhost]:5701 [dev] [3.7.8] Node is already shutting down... Waiting for shutdown process to complete...


Here is the console output,
java.lang.NullPointerException
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto$Builder.setSrc(ClientNamenodeProtocolProtos.java:47453)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:768)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
	at com.sun.proxy.$Proxy13.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2123)
	at org.smartdata.actions.hdfs.ReadFileAction.execute(ReadFileAction.java:56)
	at org.smartdata.actions.SmartAction.run(SmartAction.java:120)
	at org.smartdata.server.engine.cmdlet.Cmdlet.runAllActions(Cmdlet.java:95)
	at org.smartdata.server.engine.cmdlet.Cmdlet.run(Cmdlet.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto$Builder.setSrc(ClientNamenodeProtocolProtos.java:47453)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:768)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
	at com.sun.proxy.$Proxy13.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2123)
	at org.smartdata.actions.hdfs.ReadFileAction.execute(ReadFileAction.java:56)
	at org.smartdata.actions.SmartAction.run(SmartAction.java:120)
	at org.smartdata.server.engine.cmdlet.Cmdlet.runAllActions(Cmdlet.java:95)
	at org.smartdata.server.engine.cmdlet.Cmdlet.run(Cmdlet.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-25" java.lang.OutOfMemoryError: PermGen space
Exception in thread "Thread-26" java.lang.OutOfMemoryError: PermGen space
Exception in thread "Thread-0" java.lang.OutOfMemoryError: PermGen space
Exception in thread "hz.ShutdownThread" java.lang.OutOfMemoryError: PermGen space
```

**Comment by huafengw** [comment]
I think it's not cause by read action's exception. Please note
```
FAILED org.eclipse.jetty.server.Server@c06d2b7: java.lang.OutOfMemoryError: PermGen space
java.lang.OutOfMemoryError: PermGen space
```

**Comment by ChenSammi** [comment]
Maybe.  But I only executed read action with nonexistent file before try invalid format argument.  So it’s very likely out-of-memory is caused by “read” action or logic it trigged.

**Comment by huafengw** [comment]
I think we can close this one?

**Comment by ChenSammi** [comment]
Sure. I will close it.
