### ISSUE TITLE
Cmdlet terminal status report sometimes lost

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#662]

**Comment by huafengw** [comment]
Further investigation shows only move action will suffer from this problem

**Comment by huafengw** [comment]
```
java.lang.NoClassDefFoundError: com/sun/tools/javac/util/Log
	at org.smartdata.actions.hdfs.move.MoverCli.run(MoverCli.java:129)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.smartdata.actions.hdfs.move.MoverBasedMoveRunner.move(MoverBasedMoveRunner.java:47)
	at org.smartdata.actions.hdfs.move.MoverBasedMoveRunner.move(MoverBasedMoveRunner.java:41)
	at org.smartdata.actions.hdfs.MoveFileAction.execute(MoveFileAction.java:68)
	at org.smartdata.actions.SmartAction.run(SmartAction.java:125)
	at org.smartdata.server.engine.cmdlet.Cmdlet.runAllActions(Cmdlet.java:95)
	at org.smartdata.server.engine.cmdlet.Cmdlet.run(Cmdlet.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.util.Log
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```
