### ISSUE TITLE
database can not save action log or result if it's too long

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#687]
```
Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update actions set result = ?, log = ?, successful = ?, create_time = ?, finished = ?, finish_time = ?, progress = ? where aid = ?]; Data truncation: Data too long for column 'log' at row 1; nested exception is java.sql.BatchUpdateException: Data truncation: Data too long for column 'log' at row 1
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
        at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
        at org.smartdata.metastore.dao.ActionDao.update(ActionDao.java:135)
        at org.smartdata.metastore.MetaStore.updateActionsTable(MetaStore.java:665)
        ... 13 more
```

**Comment by littlezhou** [comment]
Done!
