### ISSUE TITLE
NullPointerException reported out in MetaStore

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#749]
I think the reason of the NullPointerException came out, is triggered by the unable to lock t he "mover".
Everything seems OK but the UI fails to show the "hot files".  Part of the SSM is not functioning well but user doesn't get any warning to this and everything seems OK, but actually not.  

2017-07-19 09:40:27,158 ERROR org.smartdata.hdfs.HdfsStatesUpdateService.checkAndMarkRunning 138: Unable to lock 'mover', please stop 'mover' first.
2017-07-19 09:40:27,159 INFO org.smartdata.server.engine.StatesManager.initStatesUpdaterService 180: Failed to create states updater service.
2017-07-19 09:40:27,159 INFO org.smartdata.server.engine.StatesManager.init 85: Initialized.
2017-07-19 09:40:27,166 INFO org.smartdata.server.engine.RuleManager.init 220: Initializing ...
2017-07-19 09:40:27,170 INFO org.smartdata.server.engine.RuleManager.init 231: Initialized. Totally 14 rules loaded from DataBase.
2017-07-19 09:40:27,170 INFO org.smartdata.server.engine.StatesManager.start 93: Starting ...
2017-07-19 09:40:27,170 INFO org.smartdata.server.engine.StatesManager.start 99: Started.
2017-07-19 09:40:27,171 INFO org.smartdata.server.engine.RuleManager.start 254: Starting ...
2017-07-19 09:40:27,264 INFO org.smartdata.server.engine.RuleManager.start 267: Started. 1 rules launched for execution.
2017-07-19 09:40:27,264 INFO org.apache.hadoop.ipc.Server.run 951: IPC Server Responder: starting
2017-07-19 09:40:27,264 INFO org.apache.hadoop.ipc.Server.run 798: IPC Server listener on 7042: starting
2017-07-19 09:40:27,745 INFO org.smartdata.server.web.SmartHttpServer.start 50: Please browse to http://0.0.0.0:7045 to see the web UI
2017-07-19 09:55:45,555 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:45,793 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:45,847 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:45,900 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:48,453 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:53,918 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:54,009 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:55,002 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:55,095 INFO org.apache.hadoop.ipc.Server.call 594: Call: protocol=org.smartdata.protocol.protocolbuffer.ClientProtocolProtoBuffer, method=reportFileAccessEvent
2017-07-19 09:55:55,996 ERROR org.smartdata.metastore.dao.AccessEventAggregator.createTable 96: Create Table accessCount_1500483350000_1500483355000
org.smartdata.metastore.MetaStoreException: java.lang.NullPointerException
        at org.smartdata.metastore.MetaStore.getFileIDs(MetaStore.java:254)
        at org.smartdata.metastore.dao.AccessEventAggregator.createTable(AccessEventAggregator.java:93)
        at org.smartdata.metastore.dao.AccessEventAggregator.addAccessEvents(AccessEventAggregator.java:64)
        at org.smartdata.metastore.dao.AccessCountTableManager.onAccessEventsArrived(AccessCountTableManager.java:113)
        at org.smartdata.server.engine.data.AccessEventFetcher$FetchTask.run(AccessEventFetcher.java:99)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

**Comment by littlezhou** [comment]
but i don't know why at org.smartdata.metastore.MetaStore.getFileIDs(MetaStore.java:254) try block NPE

**Comment by littlezhou** [comment]
Done!
