### ISSUE TITLE
Block EC: build native only when -Pnative specified

### ISSUE THREAD

**Issue by drankye** [Intel-bigdata/SSM#849]
Otherwise somebody like will fail like below:
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (compile-ms-winutils) @ smart-blockec ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "msbuild" (in directory "C:\work\projects\ssm\smart-blockec"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SmartData Project .................................. SUCCESS [  2.488 s]
[INFO] smart-metrics ...................................... SUCCESS [  4.564 s]
[INFO] smart-common ....................................... SUCCESS [ 12.374 s]
[INFO] smart-actions ...................................... SUCCESS [  0.468 s]
[INFO] smart-metastore .................................... SUCCESS [  2.741 s]
[INFO] smart-client ....................................... SUCCESS [  0.761 s]
[INFO] smart-admin ........................................ SUCCESS [  0.203 s]
[INFO] smart-dfsclient .................................... SUCCESS [  0.596 s]
[INFO] smart-rule ......................................... SUCCESS [  0.438 s]
[INFO] smart-hdfs ......................................... SUCCESS [  0.302 s]
[INFO] smart-engine ....................................... SUCCESS [  2.850 s]
[INFO] Zeppelin ........................................... SUCCESS [  3.988 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 11.981 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [  9.876 s]
[INFO] Zeppelin: Server ................................... SUCCESS [ 14.305 s]
[INFO] smart-server ....................................... SUCCESS [ 21.277 s]
[INFO] Zeppelin: Display system apis ...................... SUCCESS [  2.192 s]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 14.819 s]
[INFO] smart-agent ........................................ SUCCESS [  0.862 s]
[INFO] smart-blockec ...................................... FAILURE [  2.424 s]
[INFO] smart-dist ......................................... SKIPPED
[INFO] smart-integration .................................. SKIPPED
[INFO] smart-alluxio ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:50 min
[INFO] Finished at: 2017-08-03T09:53:08+08:00
[INFO] Final Memory: 120M/1101M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (compile-ms-winutils) on project smart-blockec: Command execution failed.: Cannot run program "msbuild" (in directory "C:\work\projects\ssm\smart-blockec"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :smart-blockec
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

**Comment by drankye** [comment]
Done already.
