### ISSUE TITLE
Can not start SmartServer

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#928]
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.smartdata.hdfs.CompatibilityHelper27
        at org.smartdata.hdfs.CompatibilityHelperLoader.create(CompatibilityHelperLoader.java:54)
        at org.smartdata.hdfs.CompatibilityHelperLoader.getHelper(CompatibilityHelperLoader.java:42)
        at org.smartdata.hdfs.action.move.StorageMap.<init>(StorageMap.java:41)
        at org.smartdata.hdfs.metric.fetcher.DatanodeStorageReportProcTask.<init>(DatanodeStorageReportProcTask.java:50)
        at org.smartdata.hdfs.metric.fetcher.DataNodeInfoFetcher.start(DataNodeInfoFetcher.java:56)
        at org.smartdata.hdfs.HdfsStatesUpdateService.start(HdfsStatesUpdateService.java:92)
        at org.smartdata.server.engine.StatesManager.start(StatesManager.java:96)
        at org.smartdata.server.SmartEngine.start(SmartEngine.java:77)
        at org.smartdata.server.SmartServer.startEngines(SmartServer.java:234)
        at org.smartdata.server.SmartServer.run(SmartServer.java:219)
        at org.smartdata.server.SmartServer.processWith(SmartServer.java:137)
        at org.smartdata.server.SmartServer.launchWith(SmartServer.java:324)
        at org.smartdata.server.SmartServer.main(SmartServer.java:330)
        at org.smartdata.server.SmartDaemon.start(SmartDaemon.java:43)
        at org.smartdata.server.SmartDaemon.main(SmartDaemon.java:62)
Caused by: java.lang.ClassNotFoundException: org.smartdata.hdfs.CompatibilityHelper27
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.smartdata.hdfs.CompatibilityHelperLoader.create(CompatibilityHelperLoader.java:50)
        ... 14 more

```

**Comment by qiyuangong** [comment]
Solved by adding `-Phadoop-2.7`. Thanks @huafengw 
Issue closed.
