### ISSUE TITLE
smart-init failed with mysql5.7.19

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#932]
Change the property_name from max 3072 to 512

2017-08-16 03:21:36,777 DEBUG org.smartdata.metastore.utils.MetaStoreUtils.initializeDataBase 274: CREATE TABLE global_config (
 cid INTEGER PRIMARY KEY AUTO_INCREMENT,
 property_name varchar(3072) NOT NULL UNIQUE,
 property_value varchar(3072) NOT NULL
) ;
2017-08-16 03:21:36,792 ERROR org.smartdata.server.SmartServer.main 350: Failed to create SmartServer
org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at org.smartdata.metastore.MetaStore.initializeDataBase(MetaStore.java:867)
        at org.smartdata.metastore.MetaStore.formatDataBase(MetaStore.java:875)
        at org.smartdata.metastore.utils.MetaStoreUtils.formatDatabase(MetaStoreUtils.java:301)
        at org.smartdata.server.SmartServer.processWith(SmartServer.java:129)
        at org.smartdata.server.SmartServer.launchWith(SmartServer.java:324)
        at org.smartdata.server.SmartServer.main(SmartServer.java:330)
        at org.smartdata.server.SmartDaemon.start(SmartDaemon.java:43)
        at org.smartdata.server.SmartDaemon.main(SmartDaemon.java:62)
Caused by: org.smartdata.metastore.MetaStoreException: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at org.smartdata.metastore.utils.MetaStoreUtils.initializeDataBase(MetaStoreUtils.java:278)
        at org.smartdata.metastore.MetaStore.initializeDataBase(MetaStore.java:865)
        ... 7 more
Caused by: org.smartdata.metastore.MetaStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at org.smartdata.metastore.utils.MetaStoreUtils.executeSql(MetaStoreUtils.java:288)
        at org.smartdata.metastore.utils.MetaStoreUtils.initializeDataBase(MetaStoreUtils.java:275)

**Comment by littlezhou** [comment]
Solved.
