### ISSUE TITLE
Mover to SSD fails due to SSD not configured

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#945]
Currently, if SSD is not configured, SSM will not give any information/warning until a `move to SSD` action is triggered. Under this circumstance, all mover actions related to SSD will fail.

```
Action starts at Thu Aug 17 00:57:59 EDT 2017 : /test/data_10MB -> ALL_SSD java.io.IOException: Mover plan not specified. at org.smartdata.hdfs.action.move.MoverBasedMoveRunner.move(MoverBasedMoveRunner.java:64) at org.smartdata.hdfs.action.move.MoverBasedMoveRunner.move(MoverBasedMoveRunner.java:55) at org.smartdata.hdfs.action.MoveFileAction.execute(MoveFileAction.java:78) at org.smartdata.action.SmartAction.run(SmartAction.java:124) at org.smartdata.server.engine.cmdlet.Cmdlet.runAllActions(Cmdlet.java:95) at org.smartdata.server.engine.cmdlet.Cmdlet.run(Cmdlet.java:109) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:748) 
```

**Comment by mkbhanda** [comment]
it is a form of lazy evaluation, also allows creating rules and SSD configuration in any order. May be the best solution here is just an error message sayign no SSDs configured.
