### ISSUE TITLE
Mover fails randomly on large file when submit multiple mover actions

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#957]
I guess it may be caused by storage types.
```
File  offset = 0, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.53:50010[DISK] 192.168.50.54:50010[SSD] } File offset = 67108864, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.54:50010[SSD] 192.168.50.53:50010[DISK] }
```

```
{u'stateChangedTime': 1503042419420, u'parameters': u'archive -file  /test/data_1GB', u'cid': 90, u'state': u'FAILED', u'generateTime': 1503042418527, u'aids': [88], u'rid': 0}
{u'stateChangedTime': 1503042420419, u'parameters': u'checkstorage -file  /test/data_1GB', u'cid': 91, u'state': u'DONE', u'generateTime': 1503042419544, u'aids': [89], u'rid': 0}
{u'stateChangedTime': 1503042422424, u'parameters': u'archive -file  /test/data_10MB', u'cid': 92, u'state': u'DONE', u'generateTime': 1503042420558, u'aids': [90], u'rid': 0}
{u'stateChangedTime': 1503042423415, u'parameters': u'checkstorage -file  /test/data_10MB', u'cid': 93, u'state': u'DONE', u'generateTime': 1503042422428, u'aids': [91], u'rid': 0}
{u'stateChangedTime': 1503042425422, u'parameters': u'onessd -file  /test/data_64MB', u'cid': 94, u'state': u'DONE', u'generateTime': 1503042423443, u'aids': [92], u'rid': 0}
{u'stateChangedTime': 1503042426414, u'parameters': u'checkstorage -file  /test/data_64MB', u'cid': 95, u'state': u'DONE', u'generateTime': 1503042425426, u'aids': [93], u'rid': 0}
{u'stateChangedTime': 1503042427419, u'parameters': u'allssd -file  /test/data_1GB', u'cid': 96, u'state': u'FAILED', u'generateTime': 1503042426441, u'aids': [94], u'rid': 0}
{u'stateChangedTime': 1503042428416, u'parameters': u'checkstorage -file  /test/data_1GB', u'cid': 97, u'state': u'DONE', u'generateTime': 1503042427456, u'aids': [95], u'rid': 0}
{u'stateChangedTime': 1503042429421, u'parameters': u'archive -file  /test/data_10MB', u'cid': 98, u'state': u'DONE', u'generateTime': 1503042428471, u'aids': [96], u'rid': 0}
{u'stateChangedTime': 1503042430414, u'parameters': u'checkstorage -file  /test/data_10MB', u'cid': 99, u'state': u'DONE', u'generateTime': 1503042429487, u'aids': [97], u'rid': 0}
{u'stateChangedTime': 1503042431421, u'parameters': u'onessd -file  /test/data_64MB', u'cid': 100, u'state': u'DONE', u'generateTime': 1503042430502, u'aids': [98], u'rid': 0}
{u'stateChangedTime': 1503042432414, u'parameters': u'checkstorage -file  /test/data_64MB', u'cid': 101, u'state': u'DONE', u'generateTime': 1503042431517, u'aids': [99], u'rid': 0}
{u'stateChangedTime': 1503042433419, u'parameters': u'onessd -file  /test/data_1GB', u'cid': 102, u'state': u'FAILED', u'generateTime': 1503042432533, u'aids': [100], u'rid': 0}
{u'stateChangedTime': 1503042434416, u'parameters': u'checkstorage -file  /test/data_1GB', u'cid': 103, u'state': u'DONE', u'generateTime': 1503042433548, u'aids': [101], u'rid': 0}
{u'stateChangedTime': 1503042435422, u'parameters': u'archive -file  /test/data_10MB', u'cid': 104, u'state': u'DONE', u'generateTime': 1503042434563, u'aids': [102], u'rid': 0}
{u'stateChangedTime': 1503042436414, u'parameters': u'checkstorage -file  /test/data_10MB', u'cid': 105, u'state': u'DONE', u'generateTime': 1503042435578, u'aids': [103], u'rid': 0}
{u'stateChangedTime': 1503042437421, u'parameters': u'onessd -file  /test/data_64MB', u'cid': 106, u'state': u'DONE', u'generateTime': 1503042436593, u'aids': [104], u'rid': 0}
{u'stateChangedTime': 1503042438414, u'parameters': u'checkstorage -file  /test/data_64MB', u'cid': 107, u'state': u'DONE', u'generateTime': 1503042437609, u'aids': [105], u'rid': 0}
```

```
Action starts at Fri Aug 18 15:49:11 CST 2017 : /test/data_64MB -> ALL_SSD java.io.IOException: Mover plan not specified. 	at org.smartdata.hdfs.action.move.MoverBasedMoveRunner.move(MoverBasedMoveRunner.java:64) 	at org.smartdata.hdfs.action.move.MoverBasedMoveRunner.move(MoverBasedMoveRunner.java:55) 	at org.smartdata.hdfs.action.MoveFileAction.execute(MoveFileAction.java:78) 	at org.smartdata.action.SmartAction.run(SmartAction.java:124) 	at org.smartdata.server.engine.cmdlet.Cmdlet.runAllActions(Cmdlet.java:95) 	at org.smartdata.server.engine.cmdlet.Cmdlet.run(Cmdlet.java:109) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 	at java.util.concurrent.FutureTask.run(FutureTask.java:262) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 	at java.lang.Thread.run(Thread.java:745)
--
```
```

File  offset = 0, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.53:50010[DISK] 192.168.50.54:50010[SSD] } File offset = 67108864, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.54:50010[SSD] 192.168.50.53:50010[DISK] } File offset = 134217728, Block locations = {192.168.50.54:50010[DISK]  192.168.50.53:50010[ARCHIVE] 192.168.50.52:50010[SSD] } File offset = 201326592, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.54:50010[ARCHIVE] 192.168.50.53:50010[ARCHIVE] } File offset = 268435456, Block locations = {192.168.50.54:50010[ARCHIVE]  192.168.50.53:50010[ARCHIVE] 192.168.50.52:50010[ARCHIVE] } File offset = 335544320, Block locations = {192.168.50.53:50010[ARCHIVE]  192.168.50.52:50010[SSD] 192.168.50.54:50010[DISK] } File offset = 402653184, Block locations = {192.168.50.53:50010[DISK]  192.168.50.54:50010[SSD] 192.168.50.52:50010[ARCHIVE] } File offset = 469762048, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.54:50010[DISK] 192.168.50.53:50010[SSD] } File offset = 536870912, Block locations = {192.168.50.53:50010[ARCHIVE]  192.168.50.54:50010[SSD] 192.168.50.52:50010[DISK] } File offset = 603979776, Block locations = {192.168.50.54:50010[DISK]  192.168.50.53:50010[ARCHIVE] 192.168.50.52:50010[SSD] } File offset = 671088640, Block locations = {192.168.50.53:50010[DISK]  192.168.50.54:50010[SSD] 192.168.50.52:50010[ARCHIVE] } File offset = 738197504, Block locations = {192.168.50.54:50010[SSD]  192.168.50.53:50010[ARCHIVE] 192.168.50.52:50010[DISK] } File offset = 805306368, Block locations = {192.168.50.53:50010[ARCHIVE]  192.168.50.52:50010[ARCHIVE] 192.168.50.54:50010[ARCHIVE] } File offset = 872415232, Block locations = {192.168.50.54:50010[ARCHIVE]  192.168.50.53:50010[SSD] 192.168.50.52:50010[DISK] } File offset = 939524096, Block locations = {192.168.50.52:50010[ARCHIVE]  192.168.50.54:50010[SSD] 192.168.50.53:50010[DISK] } File offset = 1006632960, Block locations =  {192.168.50.53:50010[ARCHIVE] 192.168.50.54:50010[ARCHIVE]  192.168.50.52:50010[ARCHIVE] }
--
Log


```

**Comment by qiyuangong** [comment]
Already done. Issue closed.
