### ISSUE TITLE
Trunk build fails and requires Maven version 3.1.1

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#975]
```
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.0.0:clean (flatten.clean) on project smart-zeppelin: The plugin org.codehaus.mojo:flatten-maven-plugin:1.0.0 requires Maven version 3.1.1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.0.0:clean (flatten.clean) on project smart-zeppelin: The plugin org.codehaus.mojo:flatten-maven-plugin:1.0.0 requires Maven version 3.1.1
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:170)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginIncompatibleException: The plugin org.codehaus.mojo:flatten-maven-plugin:1.0.0 requires Maven version 3.1.1
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.checkRequiredMavenVersion(DefaultMavenPluginManager.java:283)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:166)
        ... 19 more

```

**Comment by qiyuangong** [comment]
```org.codehaus.mojo:flatten-maven-plugin:1.0.0 requires Maven version 3.1.1```
Need to add a notice to BUILDING.

**Comment by qiyuangong** [comment]
Added requirement in deploy guide. Thanks @ChenSammi . Issued closed.
